name: ogs-environment
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ogs=6.5.5
  - ogstools=0.7.0
  - seaborn
  - jupytext
  - nbgitpuller
  - ipywidgets
  - gmsh
  - black
  - isort
  - pandoc
  - pip
  - pip:
    - jupyterlab-code-formatter
    - VTUinterface>=0.704
